{
 "title": "MyDashboard",
 "refresh": "25s",
 "panels": [
  { "title": "Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recording",
   "type": "timeseries",
   "targets": [
    {
     "expr": "recordingAll{exported_instance=\"MyInstance\"}",
     "legendFormat": "{{__name__}} - {{exported_job}}"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "timeseries",
   "targets": [
    {
     "expr": "traceAll{exported_job=\"MyInstance\"}",
     "legendFormat": "{{__name__}} - {{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU ALL",
   "type": "timeseries",
   "targets": [
    {
     "expr": "cpu_usage_all{exported_instance=\"MyInstance\"}",
     "legendFormat": "{{__name__}} - {{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "targets": [
    {
     "expr": "cpu_usage{exported_instance=\"MyInstance\"}",
     "legendFormat": "{{Name}} - {{PID}} - {{exported_job}}"
    }
   ]
  },
  {
   "title": "MEMORY ALL",
   "type": "timeseries",
   "targets": [
    {
     "expr": "memmory_usage_all{exported_instance=\"MyInstance\"}",
     "legendFormat": "{{__name__}} - {{exported_job}}"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "timeseries",
   "targets": [
    {
     "expr": "memmory_usage{exported_instance=\"MyInstance\"}",
     "legendFormat": "{{Name}} - {{PID}} - {{exported_job}}"
    }
   ]
  },
  {
   "title": "MEMORY RES (MB)",
   "type": "timeseries",
   "targets": [
    {
     "expr": "memmory_res_usage{exported_instance=\"MyInstance\"}",
     "legendFormat": "{{Name}} - {{PID}} - {{exported_job}}"
    }
   ]
  }
 ]
}